config-version: 1

blacklisted-worlds:
  - "world1"

max-blocks: 64

whitelisted-ores:
- "coal ore"
- "copper ore"
- "diamond ore"
- "emerald ore"
- "gold ore"
- "iron ore"
- "lapis lazuli ore"
- "redstone ore"
- "deepslate coal ore"
- "deepslate copper ore"
- "deepslate diamond ore"
- "deepslate emerald ore"
- "deepslate gold ore"
- "deepslate iron ore"
- "deepslate lapis lazuli ore"
- "deepslate redstone ore"
- "nether quartz ore"
- "nether gold ore"
- "oak log"
- "acacia log"
- "birch log"
- "spruce log"
- "dark oak log"
- "mangrove log"
- "cherry log"
- "pale oak log"
- "crimson stem"
- "warped stem"
- "pale oak log"
- "crimson stem"
- "warped stem"


blacklisted-ores:
  - "gold ore"
  - "jungle log"
